# Makefile for Linux_DnsResourceRecord
# (Pegasus flavor)

include ../../setting.cmpi

install:
	cimmofl -I. -aE -nroot/cimv2 Linux_DnsResourceRecord.mof
	if [ -f Linux_DnsResourceRecordRepository.mof ]; then \
		cimmofl -I. -nIBMShadow/cimv2 Linux_DnsResourceRecordRepository.mof; \
	fi
	if [ -f Linux_DnsResourceRecordRegister.mof ]; then \
		cimmofl -I. -nroot/PG_InterOp Linux_DnsResourceRecordRegister.mof; \
	fi

uninstall:
	
