# Makefile for Linux_DnsResourceRecord
# (Standalone flavor)

include ../../setting.cmpi

install: 
	install -m 644 Linux_DnsResourceRecord*.mof $(CIMOMMOF)

uninstall:
	$(RM) $(CIMOMMOF)/Linux_DnsResourceRecord*.mof
