# Makefile for Linux_DnsQueryACLForService
# (Standalone flavor)

include ../../setting.cmpi

install: 
	install -m 644 Linux_DnsQueryACLForService*.mof $(CIMOMMOF)

uninstall:
	$(RM) $(CIMOMMOF)/Linux_DnsQueryACLForService*.mof
