// ===================================================================
// Title:	    DNS Test Instances
// Filename:	    DnsInstance-1.19.mof
// Date:	    Mai 14. 2005
// Author:	    Rodrigo Ceron <rceron@br.ibm.com>
// Contributors:
// ===================================================================


// For testing purposes, all class attributes should be used


// ==================
// Dns Zone instances
// ==================

instance of Linux_DnsHintZone
{
  Name                       = ".";
  Type                       = 5;
  ResourceRecordFile         = "named.root";
};

instance of Linux_DnsForwardZone
{
  Name			     = "forward";
  Type			     = "4";
  ResourceRecordFile	     = "forwardzone.zone";
  Forward		     = 2;
  Forwarders                 = {"1.1.1.1","1.1.1.2"};
};


instance of Linux_DnsMasterZone
{
  Name                       = "localhost";
  Type                       = 1;
  ResourceRecordFile         = "localhost.zone";
  Contact                    = "ceron@localhost";
  SerialNumber               = "42";
  Refresh                    = 2;
  Retry                      = 3;
  Expire                     = 4;
  NegativeCachingTTL         = 5;
  Forward		     = 2;
  Forwarders                 = {"1.1.1.1","1.1.1.2"};
};


instance of Linux_DnsMasterZone
{
  Name                       = "localdomain";
  Type                       = 1;
  ResourceRecordFile         = "localdomain.zone";
  Contact                    = "ceron.localdomain";
  SerialNumber               = "42";
  Refresh                    = 2;
  Retry                      = 3;
  Expire                     = 4;
  NegativeCachingTTL         = 5;
  Forward		     = 1;
  Forwarders                 = {"1.1.1.1","1.1.1.2"};
};


instance of Linux_DnsMasterZone
{
  Name                       = "0.0.127.in-addr.arpa";
  Type                       = 1;
  ResourceRecordFile         = "127.0.0.zone";
  Contact                    = "ceron.0.0.127.in-addr.arpa";
  SerialNumber               = "42";
  Refresh                    = 2;
  Retry                      = 3;
  Expire                     = 4;
  NegativeCachingTTL         = 5;
  Forward		     = 2;
  Forwarders                 = {"1.1.1.1","1.1.1.2"};
};


instance of Linux_DnsMasterZone
{
  Name                       = "1.0.127.in-addr.arpa";
  Type                       = 1;
  ResourceRecordFile         = "127.0.0.zone";
  Contact                    = "ceron.1.0.127.in-addr.arpa";
  SerialNumber               = "42+1";
  Refresh                    = 12;
  Retry                      = 13;
  Expire                     = 14;
  NegativeCachingTTL         = 15;
  Forward		     = 2;
  Forwarders                 = {"1.1.1.1","1.1.1.2"};
};


instance of Linux_DnsMasterZone
{
  Name                       = "sanctuary.com";
  Type                       = 1;
  ResourceRecordFile         = "sanctuary.com.zone";
  Contact                    = "ceron.sanctuary.com";
  SerialNumber               = "2005063010";
  Refresh                    = 12;
  Retry                      = 13;
  Expire                     = 14;
  NegativeCachingTTL         = 15;
  Forward		     = 2;
  Forwarders                 = {"1.1.1.1","1.1.1.2"};
};


instance of Linux_DnsMasterZone
{
  Name                       = "hades.com";
  Type                       = 1;
  ResourceRecordFile         = "hades.com.zone";
  Contact                    = "ceron.hades.com";
  SerialNumber               = "2005063010";
  Refresh                    = 12;
  Retry                      = 13;
  Expire                     = 14;
  NegativeCachingTTL         = 15;
  Forward		     = 2;
  Forwarders                 = {"1.1.1.1","1.1.1.2"};
};


instance of Linux_DnsSlaveZone
{
  Name			     = "slavezone";
  ResourceRecordFile	     = "slavezone.zone";
  Type			     = 2;
  Forward		     = 1;
  Forwarders                 = {"1.1.1.1","1.1.1.2"};
};


// ==========================
// Resource Record instances
// ========================== 

instance of Linux_DnsResourceRecord
{
  ZoneName                   = "localhost";
  Name                       = "localhostrr1";
  TTL                        = 10;
  Type                       = 2;
  Family		     = 0;
  Value                      = "curly.ltc.ic.unicamp.br";
  Description                = "Sample Resource Record";
};

instance of Linux_DnsResourceRecord
{
  ZoneName                   = "localhost";
  Name                       = "localhostrr2";
  TTL                        = 101;
  Type                       = 1;
  Value                      = "curly.ltc.ic.unicamp.br";
  Description                = "Sample Resource Record2";
  Family		     = 1;

};


instance of Linux_DnsResourceRecord
{
  ZoneName                   = "slavezone";
  Name                       = "slavezonerr1";
  TTL                        = 101;
  Type                       = 1;
  Value                      = "larry.ltc.ic.unicamp.br";
  Description                = "Resource Record for slave zone";
  Family		     = 1;

};


instance of Linux_DnsResourceRecord
{
  ZoneName                   = ".";
  Name                       = "hintzonerr1";
  TTL                        = 34;
  Type                       = 1;
  Family		     = 0;
  Value                      = "curly.ltc.ic.unicamp.br";
  Description                = "Sample Resource Record 4";
};


instance of Linux_DnsResourceRecord
{
  ZoneName                   = "forward";
  Name                       = "forwardzonerr1";
  TTL                        = 54;
  Type                       = 1;
  Value                      = "larry.ltc.ic.unicamp.br";
  Description                = "Resource Record for forward zone";
  Family		     = 1;

};


instance of Linux_DnsResourceRecord
{
  ZoneName                   = "localdomain";
  Name                       = "localdomainzonerr1";
  TTL                        = 26;
  Type                       = 1;
  Value                      = "larry.ltc.ic.unicamp.br";
  Description                = "Resource Record for localdomain zone";
  Family		     = 1;

};


instance of Linux_DnsResourceRecord
{
  ZoneName                   = "0.0.127.in-addr.arpa";
  Name                       = "0.0.127zonerr1";
  TTL                        = 76;
  Type                       = 1;
  Value                      = "larry.ltc.ic.unicamp.br";
  Description                = "Resource Record for 0.0.127 zone";
  Family		     = 1;

};


instance of Linux_DnsResourceRecord
{
  ZoneName                   = "1.0.127.in-addr.arpa";
  Name                       = "1.0.127zonerr1";
  TTL                        = 82;
  Type                       = 1;
  Value                      = "larry.ltc.ic.unicamp.br";
  Description                = "Resource Record for 0.0.127 zone";
  Family		     = 1;

};


// RRs for sanctuary.com

instance of Linux_DnsResourceRecord
{
  ZoneName                   = "sanctuary.com";
  Name                       = "sanctuary.com.";
  TTL                        = 82;
  Type                       = 3;
  Value                      = "shion";
  Description                = "name server";
  Family		     = 1;

};

instance of Linux_DnsResourceRecord
{
  ZoneName                   = "sanctuary.com";
  Name                       = "shion";
  TTL                        = 82;
  Type                       = 6;
  Value                      = "12.12.12.13";
  Description                = "name server";
  Family		     = 1;

};

instance of Linux_DnsResourceRecord
{
  ZoneName                   = "sanctuary.com";
  Name                       = "mu";
  TTL                        = 82;
  Type                       = 6;
  Value                      = "12.12.12.1";
  Description                = "";
  Family		     = 1;
};

instance of Linux_DnsResourceRecord
{
  ZoneName                   = "sanctuary.com";
  Name                       = "aldebaran";
  TTL                        = 82;
  Type                       = 6;
  Value                      = "12.12.12.2";
  Description                = "";
  Family		     = 1;
};

instance of Linux_DnsResourceRecord
{
  ZoneName                   = "sanctuary.com";
  Name                       = "saga";
  TTL                        = 82;
  Type                       = 6;
  Value                      = "12.12.12.3";
  Description                = "";
  Family		     = 1;
};

instance of Linux_DnsResourceRecord
{
  ZoneName                   = "sanctuary.com";
  Name                       = "deathmask";
  TTL                        = 82;
  Type                       = 6;
  Value                      = "12.12.12.4";
  Description                = "";
  Family		     = 1;
};

instance of Linux_DnsResourceRecord
{
  ZoneName                   = "sanctuary.com";
  Name                       = "aiolia";
  TTL                        = 82;
  Type                       = 6;
  Value                      = "12.12.12.5";
  Description                = "";
  Family		     = 1;
};

instance of Linux_DnsResourceRecord
{
  ZoneName                   = "sanctuary.com";
  Name                       = "shaka";
  TTL                        = 82;
  Type                       = 6;
  Value                      = "12.12.12.6";
  Description                = "";
  Family		     = 1;
};

instance of Linux_DnsResourceRecord
{
  ZoneName                   = "sanctuary.com";
  Name                       = "dohko";
  TTL                        = 82;
  Type                       = 6;
  Value                      = "12.12.12.7";
  Description                = "";
  Family		     = 1;
};

instance of Linux_DnsResourceRecord
{
  ZoneName                   = "sanctuary.com";
  Name                       = "milo";
  TTL                        = 82;
  Type                       = 6;
  Value                      = "12.12.12.8";
  Description                = "";
  Family		     = 1;
};

instance of Linux_DnsResourceRecord
{
  ZoneName                   = "sanctuary.com";
  Name                       = "aiolos";
  TTL                        = 82;
  Type                       = 6;
  Value                      = "12.12.12.9";
  Description                = "";
  Family		     = 1;
};

instance of Linux_DnsResourceRecord
{
  ZoneName                   = "sanctuary.com";
  Name                       = "shura";
  TTL                        = 82;
  Type                       = 6;
  Value                      = "12.12.12.10";
  Description                = "";
  Family		     = 1;
};

instance of Linux_DnsResourceRecord
{
  ZoneName                   = "sanctuary.com";
  Name                       = "camus";
  TTL                        = 82;
  Type                       = 6;
  Value                      = "12.12.12.11";
  Description                = "";
  Family		     = 1;
};

instance of Linux_DnsResourceRecord
{
  ZoneName                   = "sanctuary.com";
  Name                       = "afrodite";
  TTL                        = 82;
  Type                       = 6;
  Value                      = "12.12.12.12";
  Description                = "";
  Family		     = 1;
};


// RRs for hades.com

instance of Linux_DnsResourceRecord
{
  ZoneName                   = "hades.com";
  Name                       = "hades.com.";
  TTL                        = 82;
  Type                       = 3;
  Value                      = "hades";
  Description                = "name server";
  Family		     = 1;

};

instance of Linux_DnsResourceRecord
{
  ZoneName                   = "hades.com";
  Name                       = "hades";
  TTL                        = 82;
  Type                       = 6;
  Value                      = "66.66.66.1";
  Description                = "name server";
  Family		     = 1;

};


// ===============================================
// Association: Resource record belongs to a zone
// ===============================================

instance of Linux_DnsResourceRecordInZone
{
  GroupComponent = "Linux_DnsMasterZone.Name=\"hades.com\"";
  PartComponent  = "Linux_DnsResourceRecord.Name=\"hades.com.\",ZoneName=\"hades.com\",Type=3,Value=\"hades\"";
};

instance of Linux_DnsResourceRecordInZone
{
  GroupComponent = "Linux_DnsMasterZone.Name=\"hades.com\"";
  PartComponent  = "Linux_DnsResourceRecord.Name=\"hades\",ZoneName=\"hades.com\",Type=6,Value=\"66.66.66.1\"";
};


instance of Linux_DnsResourceRecordInZone
{
  GroupComponent = "Linux_DnsMasterZone.Name=\"sanctuary.com\"";
  PartComponent  = "Linux_DnsResourceRecord.Name=\"sanctuary.com.\",ZoneName=\"sanctuary.com\",Type=3,Value=\"shion\"";
};

instance of Linux_DnsResourceRecordInZone
{
  GroupComponent = "Linux_DnsMasterZone.Name=\"sanctuary.com\"";
  PartComponent  = "Linux_DnsResourceRecord.Name=\"shion\",ZoneName=\"sanctuary.com\",Type=6,Value=\"12.12.12.13\"";
};

instance of Linux_DnsResourceRecordInZone
{
  GroupComponent = "Linux_DnsMasterZone.Name=\"sanctuary.com\"";
  PartComponent  = "Linux_DnsResourceRecord.Name=\"mu\",ZoneName=\"sanctuary.com\",Type=6,Value=\"12.12.12.1\"";
};

instance of Linux_DnsResourceRecordInZone
{
  GroupComponent = "Linux_DnsMasterZone.Name=\"sanctuary.com\"";
  PartComponent  = "Linux_DnsResourceRecord.Name=\"aldebaran\",ZoneName=\"sanctuary.com\",Type=6,Value=\"12.12.12.2\"";
};

instance of Linux_DnsResourceRecordInZone
{
  GroupComponent = "Linux_DnsMasterZone.Name=\"sanctuary.com\"";
  PartComponent  = "Linux_DnsResourceRecord.Name=\"saga\",ZoneName=\"sanctuary.com\",Type=6,Value=\"12.12.12.3\"";
};

instance of Linux_DnsResourceRecordInZone
{
  GroupComponent = "Linux_DnsMasterZone.Name=\"sanctuary.com\"";
  PartComponent  = "Linux_DnsResourceRecord.Name=\"deathmask\",ZoneName=\"sanctuary.com\",Type=6,Value=\"12.12.12.4\"";
};

instance of Linux_DnsResourceRecordInZone
{
  GroupComponent = "Linux_DnsMasterZone.Name=\"sanctuary.com\"";
  PartComponent  = "Linux_DnsResourceRecord.Name=\"aiolia\",ZoneName=\"sanctuary.com\",Type=6,Value=\"12.12.12.5\"";
};

instance of Linux_DnsResourceRecordInZone
{
  GroupComponent = "Linux_DnsMasterZone.Name=\"sanctuary.com\"";
  PartComponent  = "Linux_DnsResourceRecord.Name=\"shaka\",ZoneName=\"sanctuary.com\",Type=6,Value=\"12.12.12.6\"";
};

instance of Linux_DnsResourceRecordInZone
{
  GroupComponent = "Linux_DnsMasterZone.Name=\"sanctuary.com\"";
  PartComponent  = "Linux_DnsResourceRecord.Name=\"dohko\",ZoneName=\"sanctuary.com\",Type=6,Value=\"12.12.12.7\"";
};

instance of Linux_DnsResourceRecordInZone
{
  GroupComponent = "Linux_DnsMasterZone.Name=\"sanctuary.com\"";
  PartComponent  = "Linux_DnsResourceRecord.Name=\"milo\",ZoneName=\"sanctuary.com\",Type=6,Value=\"12.12.12.8\"";
};

instance of Linux_DnsResourceRecordInZone
{
  GroupComponent = "Linux_DnsMasterZone.Name=\"sanctuary.com\"";
  PartComponent  = "Linux_DnsResourceRecord.Name=\"aiolos\",ZoneName=\"sanctuary.com\",Type=6,Value=\"12.12.12.9\"";
};

instance of Linux_DnsResourceRecordInZone
{
  GroupComponent = "Linux_DnsMasterZone.Name=\"sanctuary.com\"";
  PartComponent  = "Linux_DnsResourceRecord.Name=\"shura\",ZoneName=\"sanctuary.com\",Type=6,Value=\"12.12.12.10\"";
};

instance of Linux_DnsResourceRecordInZone
{
  GroupComponent = "Linux_DnsMasterZone.Name=\"sanctuary.com\"";
  PartComponent  = "Linux_DnsResourceRecord.Name=\"camus\",ZoneName=\"sanctuary.com\",Type=6,Value=\"12.12.12.11\"";
};

instance of Linux_DnsResourceRecordInZone
{
  GroupComponent = "Linux_DnsMasterZone.Name=\"sanctuary.com\"";
  PartComponent  = "Linux_DnsResourceRecord.Name=\"afrodite\",ZoneName=\"sanctuary.com\",Type=6,Value=\"12.12.12.12\"";
};


instance of Linux_DnsResourceRecordInZone
{
  GroupComponent = "Linux_DnsMasterZone.Name=\"localhost\"";
  PartComponent  = "Linux_DnsResourceRecord.Name=\"localhostrr1\",ZoneName=\"localhost\",Type=2,Value=\"curly.ltc.ic.unicamp.br\"";
};


instance of Linux_DnsResourceRecordInZone
{
  GroupComponent = "Linux_DnsMasterZone.Name=\"localhost\"";
  PartComponent  = "Linux_DnsResourceRecord.Name=\"localhostrr2\",ZoneName=\"localhost\",Type=1,Value=\"curly.ltc.ic.unicamp.br\"";
};


instance of Linux_DnsResourceRecordInZone
{
  GroupComponent = "Linux_DnsSlaveZone.Name=\"slavezone\"";
  PartComponent  = "Linux_DnsResourceRecord.Name=\"slavezonerr1\",ZoneName=\"slavezone\",Type=1,Value=\"larry.ltc.ic.unicamp.br\"";
};


instance of Linux_DnsResourceRecordInZone
{
  GroupComponent = "Linux_DnsHintZone.Name=\".\"";
  PartComponent  = "Linux_DnsResourceRecord.Name=\"hintzonerr1\",ZoneName=\".\",Type=1,Value=\"curly.ltc.ic.unicamp.br\"";
};


instance of Linux_DnsResourceRecordInZone
{
  GroupComponent = "Linux_DnsForwardZone.Name=\"forward\"";
  PartComponent  = "Linux_DnsResourceRecord.Name=\"forwardzonerr1\",ZoneName=\"forward\",Type=1,Value=\"larry.ltc.ic.unicamp.br\"";
};

instance of Linux_DnsResourceRecordInZone
{
  GroupComponent = "Linux_DnsMasterZone.Name=\"localdomain\"";
  PartComponent  = "Linux_DnsResourceRecord.Name=\"localdomainzonerr1\",ZoneName=\"localdomain\",Type=1,Value=\"larry.ltc.ic.unicamp.br\"";
};


instance of Linux_DnsResourceRecordInZone
{
  GroupComponent = "Linux_DnsMasterZone.Name=\"0.0.127.in-addr.arpa\"";
  PartComponent  = "Linux_DnsResourceRecord.Name=\"0.0.127zonerr1\",ZoneName=\"0.0.127.in-addr.arpa\",Type=1,Value=\"larry.ltc.ic.unicamp.br\"";
};


instance of Linux_DnsResourceRecordInZone
{
  GroupComponent = "Linux_DnsMasterZone.Name=\"1.0.127.in-addr.arpa\"";
  PartComponent  = "Linux_DnsResourceRecord.Name=\"1.0.127zonerr1\",ZoneName=\"1.0.127.in-addr.arpa\",Type=1,Value=\"larry.ltc.ic.unicamp.br\"";
};


// =====================
// Dns Service Instance
// =====================

instance of Linux_DnsService
{
   CreationClassName         = "Linux_DnsService";
   SystemCreationClassName   = "Linux_DnsService";
   SystemName                = "localhost";
   Name                      = "named";
   Started		     = false;
   StartMode		     = "Automatic";
   RunAsRoot		     = true;
};


// =======================
// Dns Address Match List
// =======================


instance of Linux_DnsAddressMatchList
{
   ServiceName               = "named";
   Name                      = "GooseHosts";
   AddressListType	     = 6;
   AddressList               = {"10.0.0.200","10.0.0.201","10.0.0.202"};
};


instance of Linux_DnsAddressMatchList
{
   ServiceName               = "named";
   Name                      = "LtcPPCHosts";
   AddressListType	     = 6;
   AddressList               = {"10.0.0.71","10.0.0.74"};
};


instance of Linux_DnsAddressMatchList
{
   ServiceName		     = "named";
   Name			     = "LonelyHost";
   AddressListType	     = 2;
   AddressList		     = {"10.0.0.99"};
};


instance of Linux_DnsAddressMatchList
{
   ServiceName               = "named";
   Name                      = "ServerHosts";
   AddressListType	     = 6;
   AddressList               = {"10.0.0.1","10.0.0.70","10.0.0.49"};
};


// =================================================================
// Association: Address Match List is in the scope of a Dns Service
// =================================================================

instance of Linux_DnsAddressMatchListOfService
{
   Antecedent = "Linux_DnsService.Name=\"named\",CreationClassName=\"Linux_DnsService\",SystemCreationClassName=\"Linux_DnsService\",SystemName=\"localhost\"";
   Dependent = "Linux_DnsAddressMatchList.Name=\"LonelyHost\",ServiceName=\"named\"";
};


instance of Linux_DnsAddressMatchListOfService
{
   Antecedent		     = "Linux_DnsService.Name=\"named\",CreationClassName=\"Linux_DnsService\",SystemCreationClassName=\"Linux_DnsService\",SystemName=\"localhost\"";
   Dependent = "Linux_DnsAddressMatchList.Name=\"GooseHosts\",ServiceName=\"named\"";
};


instance of Linux_DnsAddressMatchListOfService
{
   Antecedent		     = "Linux_DnsService.Name=\"named\",CreationClassName=\"Linux_DnsService\",SystemCreationClassName=\"Linux_DnsService\",SystemName=\"localhost\"";
   Dependent = "Linux_DnsAddressMatchList.Name=\"LtcPPCHosts\",ServiceName=\"named\"";
};


instance of Linux_DnsAddressMatchListOfService
{
   Antecedent		     = "Linux_DnsService.Name=\"named\",CreationClassName=\"Linux_DnsService\",SystemCreationClassName=\"Linux_DnsService\",SystemName=\"localhost\"";
   Dependent = "Linux_DnsAddressMatchList.Name=\"ServerHosts\",ServiceName=\"named\"";
};


// ===============================================
// ACL for Service Requests 
// ===============================================

instance of Linux_DnsQueryACLForService
{
   Element = "Linux_DnsService.Name=\"named\",CreationClassName=\"Linux_DnsService\",SystemCreationClassName=\"Linux_DnsService\",SystemName=\"localhost\"";
   Setting = "Linux_DnsAddressMatchList.Name=\"ServerHosts\",ServiceName=\"named\"";
};

instance of Linux_DnsTransferACLForService
{
   Element = "Linux_DnsService.Name=\"named\",CreationClassName=\"Linux_DnsService\",SystemCreationClassName=\"Linux_DnsService\",SystemName=\"localhost\"";
   Setting = "Linux_DnsAddressMatchList.Name=\"GooseHosts\",ServiceName=\"named\"";
};


instance of Linux_DnsRecursionACLForService
{
   Element = "Linux_DnsService.Name=\"named\",CreationClassName=\"Linux_DnsService\",SystemCreationClassName=\"Linux_DnsService\",SystemName=\"localhost\"";
   Setting = "Linux_DnsAddressMatchList.Name=\"LtcPPCHosts\",ServiceName=\"named\"";
};


instance of Linux_DnsNotifyACLForService
{
   Element = "Linux_DnsService.Name=\"named\",CreationClassName=\"Linux_DnsService\",SystemCreationClassName=\"Linux_DnsService\",SystemName=\"localhost\"";
   Setting = "Linux_DnsAddressMatchList.Name=\"GooseHosts\",ServiceName=\"named\"";
};


instance of Linux_DnsBlackholeACLForService
{
   Element = "Linux_DnsService.Name=\"named\",CreationClassName=\"Linux_DnsService\",SystemCreationClassName=\"Linux_DnsService\",SystemName=\"localhost\"";
   Setting = "Linux_DnsAddressMatchList.Name=\"LonelyHost\",ServiceName=\"named\"";
};

// ==============
// ACL for Zones
// ==============


instance of Linux_DnsAllowQueryACLForZone
{
   Element		      = "Linux_DnsMasterZone.Name=\"localdomain\"";
   Setting = "Linux_DnsAddressMatchList.Name=\"GooseHosts\",ServiceName=\"named\"";
};

instance of Linux_DnsAllowTransferACLForZone
{
   Element		      = "Linux_DnsMasterZone.Name=\"localdomain\"";
   Setting = "Linux_DnsAddressMatchList.Name=\"ServerHosts\",ServiceName=\"named\"";
};

instance of Linux_DnsAllowUpdateACLForZone
{
   Element		      = "Linux_DnsMasterZone.Name=\"localdomain\"";
   Setting = "Linux_DnsAddressMatchList.Name=\"LonelyHost\",ServiceName=\"named\"";
};

instance of Linux_DnsAllowNotifyACLForZone
{
   Element		      = "Linux_DnsSlaveZone.Name=\"slavezone\"";
   Setting = "Linux_DnsAddressMatchList.Name=\"LonelyHost\",ServiceName=\"named\"";
};
 
instance of Linux_DnsBlackholeACLForZone
{
   Element		      = "Linux_DnsMasterZone.Name=\"localdomain\"";
   Setting = "Linux_DnsAddressMatchList.Name=\"LtcPPCHosts\",ServiceName=\"named\"";
};

instance of Linux_DnsAllowTransferACLForZone
{
   Element		      = "Linux_DnsSlaveZone.Name=\"slavezone\"";
   Setting = "Linux_DnsAddressMatchList.Name=\"LonelyHost\",ServiceName=\"named\"";
};

instance of Linux_DnsAllowQueryACLForZone
{
   Element		      = "Linux_DnsSlaveZone.Name=\"slavezone\"";
   Setting = "Linux_DnsAddressMatchList.Name=\"GooseHosts\",ServiceName=\"named\"";
};


instance of Linux_DnsAllowUpdateACLForZone
{
   Element		      = "Linux_DnsMasterZone.Name=\"localdomain\"";
   Setting = "Linux_DnsAddressMatchList.Name=\"GooseHosts\",ServiceName=\"named\"";
}; 

instance of Linux_DnsBlackholeACLForZone
{
   Element		      = "Linux_DnsSlaveZone.Name=\"slavezone\"";
   Setting = "Linux_DnsAddressMatchList.Name=\"LtcPPCHosts\",ServiceName=\"named\"";
}; 


// ==========================
// Instance of Dns IPAddress
// ==========================

instance of Linux_DnsIPAddress
{
   ZoneName		      = "localdomain";
   IPAddress		      = "10.0.0.201";
   Port			      = 3334;
   SecurityKey		      = "dohko";
};


// =======================
// Masters of slave zones
// =======================


instance of Linux_DnsMastersOfSlaveZone
{

   Element		      = "Linux_DnsSlaveZone.Name=\"slavezone\"";
   Setting = "Linux_DnsIPAddress.ZoneName=\"localdomain\",IPAddress=\"10.0.0.201\"";
};


// =============================
// Instance of Dns Configuration
// =============================

instance of Linux_DnsConfiguration
{
   Name			      = "named";
   ConfigurationFile	      = "/etc/named.conf";
}; 


// =========================
// Dns Service Configuration
// =========================

instance of Linux_DnsServiceConfiguration
{
   Element = "Linux_DnsService.Name=\"named\",CreationClassName=\"Linux_DnsService\",SystemCreationClassName=\"Linux_DnsService\",SystemName=\"localhost\"";
   Configuration	      = "Linux_DnsConfiguration.Name=\"named\"";
};


// =================
// Linux Dns Setting
// =================


instance of Linux_DnsSetting
{
   Name			      = "named";
   TSIG			      = 1;
   ConfigurationDirectory     = "/etc/domain";
   TTL			      = 34;
   PortNumber		      = 3334;
   XferFormat		      = 1;
   Forward		      = 2;
   Forwarders		      = {"143.106.24.1","143.106.24.2"};
};

// ===================
// Dns Setting Context
// ===================

instance of Linux_DnsSettingContext
{
   Context = "Linux_DnsConfiguration.Name=\"named\"";
   Setting = "Linux_DnsSetting.Name=\"named\"";
};


// ===================
// Dns Element Setting
// ===================

instance of Linux_DnsElementSetting
{
   Element = "Linux_DnsService.Name=\"named\",CreationClassName=\"Linux_DnsService\",SystemCreationClassName=\"Linux_DnsService\",SystemName=\"localhost\"";
   Setting = "Linux_DnsSetting.Name=\"named\"";
};



