// ===================================================================
// This file was created using ECUTE.
//   Version 2.0 Beta-1
//   by exporting package Linux_DnsSettingContext
//   from model 
//   on 5/18/2005
// Origin of package: Manually created
// ===================================================================




// ===================================================================
// Linux_DnsSettingContext
// ===================================================================
[Association, Description (
    "Association between DNS Configuration and Setting")
    , Aggregation, IBM_HasInstances, IBM_HasProvider]
class Linux_DnsSettingContext : CIM_SettingContext {

    [Description ("The DNS Configuration"), Override ("Context")]
    Linux_DnsConfiguration REF Context;

    [Description ("The DNS Setting"), Override ("Setting")]
    Linux_DnsSetting REF Setting;
};

// ===================================================================
// end of file
// ===================================================================

