# Makefile for Linux_DnsSettingContext
# (Pegasus flavor)

include ../../setting.cmpi

install:
	cimmofl -I. -aE -nroot/cimv2 Linux_DnsSettingContext.mof
	if [ -f Linux_DnsSettingContextRepository.mof ]; then \
		cimmofl -I. -nIBMShadow/cimv2 Linux_DnsSettingContextRepository.mof; \
	fi
	if [ -f Linux_DnsSettingContextRegister.mof ]; then \
		cimmofl -I. -nroot/PG_InterOp Linux_DnsSettingContextRegister.mof; \
	fi

uninstall:
	
