# Makefile for CIM_ManagedSystemElement
# (Standalone flavor)

include ../../setting.cmpi

install: 
	install -m 644 CIM_ManagedSystemElement*.mof $(CIMOMMOF)

uninstall:
	$(RM) $(CIMOMMOF)/CIM_ManagedSystemElement*.mof
