// ===================================================================
// This file was created using ECUTE.
//   Version 2.0 Beta-1
//   by exporting package Linux_DnsMastersOfSlaveZoneRepository
//   from model 
//   on 5/18/2005
// Origin of package: Manually created
// ===================================================================




// ===================================================================
// Linux_DnsMastersOfSlaveZone
// ===================================================================
class Linux_DnsMastersOfSlaveZone {
    [Key]
    Linux_DnsSlaveZone REF Element;

    [Key]
    Linux_DnsIPAddress REF Setting;
};

// ===================================================================
// end of file
// ===================================================================

