# Makefile for Linux_DnsMastersOfSlaveZone
# (Standalone flavor)

include ../../setting.cmpi

install: 
	install -m 644 Linux_DnsMastersOfSlaveZone*.mof $(CIMOMMOF)

uninstall:
	$(RM) $(CIMOMMOF)/Linux_DnsMastersOfSlaveZone*.mof
