// ===================================================================
// This file was created using ECUTE.
//   Version 2.0 Beta-1
//   by exporting package Linux_DnsAllowTransferACLForZoneRepository
//   from model 
//   on 5/18/2005
// Origin of package: Manually created
// ===================================================================




// ===================================================================
// Linux_DnsAllowTransferACLForZone
// ===================================================================
class Linux_DnsAllowTransferACLForZone {
    [Key]
    Linux_DnsZone REF Element;

    [Key]
    Linux_DnsAddressMatchList REF Setting;
};

// ===================================================================
// end of file
// ===================================================================

