# Makefile for Linux_DnsAllowTransferACLForZone
# (Pegasus flavor)

include ../../setting.cmpi

install:
	cimmofl -I. -aE -nroot/cimv2 Linux_DnsAllowTransferACLForZone.mof
	if [ -f Linux_DnsAllowTransferACLForZoneRepository.mof ]; then \
		cimmofl -I. -nIBMShadow/cimv2 Linux_DnsAllowTransferACLForZoneRepository.mof; \
	fi
	if [ -f Linux_DnsAllowTransferACLForZoneRegister.mof ]; then \
		cimmofl -I. -nroot/PG_InterOp Linux_DnsAllowTransferACLForZoneRegister.mof; \
	fi

uninstall:
	
