# Makefile for Linux_DnsAllowTransferACLForZone
# (Standalone flavor)

include ../../setting.cmpi

install: 
	install -m 644 Linux_DnsAllowTransferACLForZone*.mof $(CIMOMMOF)

uninstall:
	$(RM) $(CIMOMMOF)/Linux_DnsAllowTransferACLForZone*.mof
