// ===================================================================
// This file was created using ECUTE.
//   Version 2.0 Beta-1
//   by exporting package Linux_DnsSettingRepository
//   from model 
//   on 8/15/2005
// Origin of package: Manually created
// ===================================================================




// ===================================================================
// Linux_DnsSetting
// ===================================================================
class Linux_DnsSetting {

    [Key]
    string Name;
};

// ===================================================================
// end of file
// ===================================================================

