# Makefile for Linux_DnsSetting
# (Standalone flavor)

include ../../setting.cmpi

install: 
	install -m 644 Linux_DnsSetting*.mof $(CIMOMMOF)

uninstall:
	$(RM) $(CIMOMMOF)/Linux_DnsSetting*.mof
