# Makefile for Linux_DnsManagedSystemElementForSetting
# (Standalone flavor)

include ../../setting.cmpi

install: 
	install -m 644 Linux_DnsManagedSystemElementForSetting*.mof $(CIMOMMOF)

uninstall:
	$(RM) $(CIMOMMOF)/Linux_DnsManagedSystemElementForSetting*.mof
