# MOF files loader
# (Standalone flavor)

include ../setting.cmpi

install: 
	install -m 644 common/*.mof $(CIMOMMOF)
	install -m 644 shadow/*.mof $(CIMOMMOF)

uninstall:
	#add here your mof files
	#$(RM) $(CIMOMMOF)/"aMOFFile".mof
