# Makefile for Linux_DnsAddressMatchList
# (Standalone flavor)

include ../../setting.cmpi

install: 
	install -m 644 Linux_DnsAddressMatchList*.mof $(CIMOMMOF)

uninstall:
	$(RM) $(CIMOMMOF)/Linux_DnsAddressMatchList*.mof
