# Makefile for Linux_DnsIPAddress
# (Pegasus flavor)

include ../../setting.cmpi

install:
	cimmofl -I. -aE -nroot/cimv2 Linux_DnsIPAddress.mof
	if [ -f Linux_DnsIPAddressRepository.mof ]; then \
		cimmofl -I. -nIBMShadow/cimv2 Linux_DnsIPAddressRepository.mof; \
	fi
	if [ -f Linux_DnsIPAddressRegister.mof ]; then \
		cimmofl -I. -nroot/PG_InterOp Linux_DnsIPAddressRegister.mof; \
	fi

uninstall:
	
