# Makefile for Linux_DnsIPAddress
# (Standalone flavor)

include ../../setting.cmpi

install: 
	install -m 644 Linux_DnsIPAddress*.mof $(CIMOMMOF)

uninstall:
	$(RM) $(CIMOMMOF)/Linux_DnsIPAddress*.mof
