// ===================================================================
// This file was created using ECUTE.
//   Version 2.0 Beta-1
//   by exporting package Linux_DnsBlackholeACLForService
//   from model 
//   on 5/18/2005
// Origin of package: Manually created
// ===================================================================




// ===================================================================
// Linux_DnsBlackholeACLForService
// ===================================================================
[Association, Description (
    "Association pointing to Address Match Lists, hosting the list of"
    " elements that are allowed to support the request type: "
    "blackhole."), IBM_HasInstances, IBM_HasProvider]
class Linux_DnsBlackholeACLForService : CIM_ElementSetting {

    [Key, Override ("Element"), Description (
        "The scoping DNS Service.")]
    Linux_DnsService REF Element;

    [Key, Override ("Setting")]
    Linux_DnsAddressMatchList REF Setting;
};

// ===================================================================
// end of file
// ===================================================================

