# Makefile for Linux_DnsBlackholeACLForService
# (Pegasus flavor)

include ../../setting.cmpi

install:
	cimmofl -I. -aE -nroot/cimv2 Linux_DnsBlackholeACLForService.mof
	if [ -f Linux_DnsBlackholeACLForServiceRepository.mof ]; then \
		cimmofl -I. -nIBMShadow/cimv2 Linux_DnsBlackholeACLForServiceRepository.mof; \
	fi
	if [ -f Linux_DnsBlackholeACLForServiceRegister.mof ]; then \
		cimmofl -I. -nroot/PG_InterOp Linux_DnsBlackholeACLForServiceRegister.mof; \
	fi

uninstall:
	
