# Makefile for Linux_DnsBlackholeACLForService
# (Standalone flavor)

include ../../setting.cmpi

install: 
	install -m 644 Linux_DnsBlackholeACLForService*.mof $(CIMOMMOF)

uninstall:
	$(RM) $(CIMOMMOF)/Linux_DnsBlackholeACLForService*.mof
