// ===================================================================
// 	Linux_DnsAddressMatchListOfService
// ===================================================================


instance of PG_ProviderModule
{
   Name = "Linux_DnsAddressMatchListOfServiceProviderModule";
   //The library name on disk
   Location = "Linux_DnsAddressMatchListOfService";
   Vendor = "SBLIM";
   Version = "2.0.0";
   InterfaceType = "CMPI";
   InterfaceVersion = "2.0.0";
};

instance of PG_Provider
{
   //The provider module as defined in PG_ProviderModule
   ProviderModuleName = "Linux_DnsAddressMatchListOfServiceProviderModule";
   // The provider name as referenced in the code
   Name = "CmpiLinux_DnsAddressMatchListOfServiceProvider";
};

instance of PG_ProviderCapabilities
{
   //The provider module as defined in PG_ProviderModule
   ProviderModuleName = "Linux_DnsAddressMatchListOfServiceProviderModule";
   //The provider name as defined in PG_Provider
   ProviderName = "CmpiLinux_DnsAddressMatchListOfServiceProvider";
   CapabilityID = "1";
   //Name of the CIM class as defined in the mof
   ClassName = "Linux_DnsAddressMatchListOfService";
   Namespaces = {"root/cimv2"};
   ProviderType = {2, 3};       // Instance Association
   SupportedProperties = NULL; // All properties
   SupportedMethods = NULL;    // All methods
};