# Makefile for Linux_DnsAddressMatchListOfService
# (Standalone flavor)

include ../../setting.cmpi

install: 
	install -m 644 Linux_DnsAddressMatchListOfService*.mof $(CIMOMMOF)

uninstall:
	$(RM) $(CIMOMMOF)/Linux_DnsAddressMatchListOfService*.mof
