// ===================================================================
// This file was created using ECUTE.
//   Version 2.0 Beta-1
//   by exporting package Linux_DnsService
//   from model 
//   on 7/27/2005
// Origin of package: Manually created
// ===================================================================




// ===================================================================
// Linux_DnsService
// ===================================================================
[Description ("Class representing the DNS service/server.")
    , IBM_HasInstances, IBM_HasProvider]
class Linux_DnsService : CIM_Service {

    [Override ("Name"), Key, Description (
        "Service process identifier."), IBM_ImplementationType (
        "Manual")]
    string Name;

    [Override ("Started"), IBM_ImplementationType ("Manual")]
    boolean Started;
};

// ===================================================================
// end of file
// ===================================================================

