# Makefile for Linux_DnsService
# (Standalone flavor)

include ../../setting.cmpi

install: 
	install -m 644 Linux_DnsService*.mof $(CIMOMMOF)

uninstall:
	$(RM) $(CIMOMMOF)/Linux_DnsService*.mof
