# Makefile for Linux_DnsService
# (Pegasus flavor)

include ../../setting.cmpi

install:
	cimmofl -I. -aE -nroot/cimv2 Linux_DnsService.mof
	if [ -f Linux_DnsServiceRepository.mof ]; then \
		cimmofl -I. -nIBMShadow/cimv2 Linux_DnsServiceRepository.mof; \
	fi
	if [ -f Linux_DnsServiceRegister.mof ]; then \
		cimmofl -I. -nroot/PG_InterOp Linux_DnsServiceRegister.mof; \
	fi

uninstall:
	
