// ===================================================================
// Extracted from Core27_Qualifiers
// ===================================================================


Qualifier Association : boolean = false, Scope(class, association),
    Flavor(disableoverride);


Qualifier Key : boolean = false, Scope(property, reference),
    Flavor(disableoverride);


