# Makefile for Linux_DnsTransferACLForService
# (Pegasus flavor)

include ../../setting.cmpi

install:
	cimmofl -I. -aE -nroot/cimv2 Linux_DnsTransferACLForService.mof
	if [ -f Linux_DnsTransferACLForServiceRepository.mof ]; then \
		cimmofl -I. -nIBMShadow/cimv2 Linux_DnsTransferACLForServiceRepository.mof; \
	fi
	if [ -f Linux_DnsTransferACLForServiceRegister.mof ]; then \
		cimmofl -I. -nroot/PG_InterOp Linux_DnsTransferACLForServiceRegister.mof; \
	fi

uninstall:
	
