// ===================================================================
// This file was created using ECUTE.
//   Version 2.0 Beta-1
//   by exporting package Linux_DnsHintZoneRepository
//   from model 
//   on 5/18/2005
// Origin of package: Manually created
// ===================================================================




// ===================================================================
// Linux_DnsHintZone
// ===================================================================
class Linux_DnsHintZone : Linux_DnsZone {

    [Key]
    string Name;
};

// ===================================================================
// end of file
// ===================================================================

