# Makefile for Linux_DnsHintZone
# (Standalone flavor)

include ../../setting.cmpi

install: 
	install -m 644 Linux_DnsHintZone*.mof $(CIMOMMOF)

uninstall:
	$(RM) $(CIMOMMOF)/Linux_DnsHintZone*.mof
