# Makefile for Linux_DnsAllowQueryACLForZone
# (Standalone flavor)

include ../../setting.cmpi

install: 
	install -m 644 Linux_DnsAllowQueryACLForZone*.mof $(CIMOMMOF)

uninstall:
	$(RM) $(CIMOMMOF)/Linux_DnsAllowQueryACLForZone*.mof
