# Makefile for Linux_DnsRecursionACLForService
# (Pegasus flavor)

include ../../setting.cmpi

install:
	cimmofl -I. -aE -nroot/cimv2 Linux_DnsRecursionACLForService.mof
	if [ -f Linux_DnsRecursionACLForServiceRepository.mof ]; then \
		cimmofl -I. -nIBMShadow/cimv2 Linux_DnsRecursionACLForServiceRepository.mof; \
	fi
	if [ -f Linux_DnsRecursionACLForServiceRegister.mof ]; then \
		cimmofl -I. -nroot/PG_InterOp Linux_DnsRecursionACLForServiceRegister.mof; \
	fi

uninstall:
	
