# Makefile for Linux_DnsRecursionACLForService
# (Standalone flavor)

include ../../setting.cmpi

install: 
	install -m 644 Linux_DnsRecursionACLForService*.mof $(CIMOMMOF)

uninstall:
	$(RM) $(CIMOMMOF)/Linux_DnsRecursionACLForService*.mof
