# Makefile for Linux_DnsAllowNotifyACLForZone
# (Standalone flavor)

include ../../setting.cmpi

install: 
	install -m 644 Linux_DnsAllowNotifyACLForZone*.mof $(CIMOMMOF)

uninstall:
	$(RM) $(CIMOMMOF)/Linux_DnsAllowNotifyACLForZone*.mof
