// ===================================================================
// 	Linux_DnsForwardZone
// ===================================================================


instance of PG_ProviderModule
{
   Name = "Linux_DnsForwardZoneProviderModule";
   //The library name on disk
   Location = "Linux_DnsForwardZone";
   Vendor = "SBLIM";
   Version = "2.0.0";
   InterfaceType = "CMPI";
   InterfaceVersion = "2.0.0";
};

instance of PG_Provider
{
   //The provider module as defined in PG_ProviderModule
   ProviderModuleName = "Linux_DnsForwardZoneProviderModule";
   // The provider name as referenced in the code
   Name = "CmpiLinux_DnsForwardZoneProvider";
};

instance of PG_ProviderCapabilities
{
   //The provider module as defined in PG_ProviderModule
   ProviderModuleName = "Linux_DnsForwardZoneProviderModule";
   //The provider name as defined in PG_Provider
   ProviderName = "CmpiLinux_DnsForwardZoneProvider";
   CapabilityID = "1";
   //Name of the CIM class as defined in the mof
   ClassName = "Linux_DnsForwardZone";
   Namespaces = {"root/cimv2"};
   ProviderType = {2, 5};       // Instance Method
   SupportedProperties = NULL; // All properties
   SupportedMethods = NULL;    // All methods
};