# Makefile for Linux_DnsForwardZone
# (Standalone flavor)

include ../../setting.cmpi

install: 
	install -m 644 Linux_DnsForwardZone*.mof $(CIMOMMOF)

uninstall:
	$(RM) $(CIMOMMOF)/Linux_DnsForwardZone*.mof
