# Makefile for Linux_DnsConfiguration
# (Standalone flavor)

include ../../setting.cmpi

install: 
	install -m 644 Linux_DnsConfiguration*.mof $(CIMOMMOF)

uninstall:
	$(RM) $(CIMOMMOF)/Linux_DnsConfiguration*.mof
