# Makefile for Linux_DnsNotifyACLForService
# (Standalone flavor)

include ../../setting.cmpi

install: 
	install -m 644 Linux_DnsNotifyACLForService*.mof $(CIMOMMOF)

uninstall:
	$(RM) $(CIMOMMOF)/Linux_DnsNotifyACLForService*.mof
