# Makefile for Linux_DnsNotifyACLForService
# (Pegasus flavor)

include ../../setting.cmpi

install:
	cimmofl -I. -aE -nroot/cimv2 Linux_DnsNotifyACLForService.mof
	if [ -f Linux_DnsNotifyACLForServiceRepository.mof ]; then \
		cimmofl -I. -nIBMShadow/cimv2 Linux_DnsNotifyACLForServiceRepository.mof; \
	fi
	if [ -f Linux_DnsNotifyACLForServiceRegister.mof ]; then \
		cimmofl -I. -nroot/PG_InterOp Linux_DnsNotifyACLForServiceRegister.mof; \
	fi

uninstall:
	
