# Makefile for Linux_DnsResourceRecordInZone
# (Standalone flavor)

include ../../setting.cmpi

install: 
	install -m 644 Linux_DnsResourceRecordInZone*.mof $(CIMOMMOF)

uninstall:
	$(RM) $(CIMOMMOF)/Linux_DnsResourceRecordInZone*.mof
