# Makefile for Linux_DnsResourceRecordInZone
# (Pegasus flavor)

include ../../setting.cmpi

install:
	cimmofl -I. -aE -nroot/cimv2 Linux_DnsResourceRecordInZone.mof
	if [ -f Linux_DnsResourceRecordInZoneRepository.mof ]; then \
		cimmofl -I. -nIBMShadow/cimv2 Linux_DnsResourceRecordInZoneRepository.mof; \
	fi
	if [ -f Linux_DnsResourceRecordInZoneRegister.mof ]; then \
		cimmofl -I. -nroot/PG_InterOp Linux_DnsResourceRecordInZoneRegister.mof; \
	fi

uninstall:
	
