# Makefile for Linux_DnsServiceConfiguration
# (Standalone flavor)

include ../../setting.cmpi

install: 
	install -m 644 Linux_DnsServiceConfiguration*.mof $(CIMOMMOF)

uninstall:
	$(RM) $(CIMOMMOF)/Linux_DnsServiceConfiguration*.mof
