# Makefile for Linux_DnsSlaveZone
# (Standalone flavor)

include ../../setting.cmpi

install: 
	install -m 644 Linux_DnsSlaveZone*.mof $(CIMOMMOF)

uninstall:
	$(RM) $(CIMOMMOF)/Linux_DnsSlaveZone*.mof
