# Makefile for Linux_DnsMasterZone
# (Standalone flavor)

include ../../setting.cmpi

install: 
	install -m 644 Linux_DnsMasterZone*.mof $(CIMOMMOF)

uninstall:
	$(RM) $(CIMOMMOF)/Linux_DnsMasterZone*.mof
