// ===================================================================
// This file was created using ECUTE.
//   Version 2.0 Beta-1
//   by exporting package CIM_CollectionOfMSEs
//   from model 
//   on 5/18/2005
// Origin of package: Manually created
// ===================================================================




// ===================================================================
// CIM_CollectionOfMSEs
// ===================================================================
[Abstract, Version ("2.6.0"), Description (
    "The CollectionOfMSEs object allows the grouping of Managed "
    "SystemElements for various identification purposes and to reduce"
    " the complexity of associating Settings and Configurations. It "
    "is abstract to require further definition and semantic "
    "refinement in subclasses. The CollectionOfMSEs object does not "
    "carry any state or status information, but only represents a "
    "grouping or 'bag' of Elements. For this reason, it is incorrect "
    "to subclass groups that have state/ status from CollectionOfMSEs"
    " - an example is CIM_Redundancy Group (which is subclassed from "
    "LogicalElement). \n"
    "Collections typically aggregate 'like'objects, but are not "
    "required to do so. They simply identify 'bags' and may represent"
    " an optimization. This is especially true with respect to their "
    "association to Settings and Configurations. Without Collections,"
    " one is forced to define individual ElementSetting "
    "andElementConfiguration associations, to tie Settings and "
    "Configuration objects to individual ManagedSystemElements. There"
    " may be much duplication in assigning the same Setting to "
    "multiple objects. In addition, using the Collection object "
    "allows the determination that the Setting and Configuration "
    "associations are indeed the same for the Collection's members. "
    "This information would otherwise be obtained by defining the "
    "Collection in a proprietary manner, and then querying the "
    "ElementSetting and ElementConfiguration associations to "
    "determine ifthe Collection set is completely covered.")]
class CIM_CollectionOfMSEs : CIM_Collection {

    [Description (
        "The identification of the Collection object. When "
        "subclassed, the CollectionID property can be overridden to "
        "be a Key property."), MaxLen (256)]
    string CollectionID;
};

// ===================================================================
// end of file
// ===================================================================

