# Makefile for CIM_CollectionOfMSEs
# (Standalone flavor)

include ../../setting.cmpi

install: 
	install -m 644 CIM_CollectionOfMSEs*.mof $(CIMOMMOF)

uninstall:
	$(RM) $(CIMOMMOF)/CIM_CollectionOfMSEs*.mof
