# Makefile for CIM_CollectionOfMSEs
# (Pegasus flavor)

include ../../setting.cmpi

install:
	cimmofl -I. -aE -nroot/cimv2 CIM_CollectionOfMSEs.mof
	if [ -f CIM_CollectionOfMSEsRepository.mof ]; then \
		cimmofl -I. -nIBMShadow/cimv2 CIM_CollectionOfMSEsRepository.mof; \
	fi
	if [ -f CIM_CollectionOfMSEsRegister.mof ]; then \
		cimmofl -I. -nroot/PG_InterOp CIM_CollectionOfMSEsRegister.mof; \
	fi

uninstall:
	
