// ===================================================================
// This file was created using ECUTE.
//   Version 2.0 Beta-1
//   by exporting package Linux_DnsElementSettingRepository
//   from model 
//   on 5/18/2005
// Origin of package: Manually created
// ===================================================================




// ===================================================================
// Linux_DnsElementSetting
// ===================================================================
class Linux_DnsElementSetting {
    [Key]
    Linux_DnsService REF Element;

    [Key]
    Linux_DnsSetting REF Setting;
};

// ===================================================================
// end of file
// ===================================================================

