# Makefile for Linux_DnsElementSetting
# (Pegasus flavor)

include ../../setting.cmpi

install:
	cimmofl -I. -aE -nroot/cimv2 Linux_DnsElementSetting.mof
	if [ -f Linux_DnsElementSettingRepository.mof ]; then \
		cimmofl -I. -nIBMShadow/cimv2 Linux_DnsElementSettingRepository.mof; \
	fi
	if [ -f Linux_DnsElementSettingRegister.mof ]; then \
		cimmofl -I. -nroot/PG_InterOp Linux_DnsElementSettingRegister.mof; \
	fi

uninstall:
	
