# Makefile for Linux_DnsElementSetting
# (Standalone flavor)

include ../../setting.cmpi

install: 
	install -m 644 Linux_DnsElementSetting*.mof $(CIMOMMOF)

uninstall:
	$(RM) $(CIMOMMOF)/Linux_DnsElementSetting*.mof
